### ISSUE TITLE
A flag to run only markdownlint without the URL checks

### ISSUE THREAD

**Issue by alexilyaev** [create-oss/check-all-markdown#2]
@giltayar Looks like the main focus of this package is to lint markdown files.  
I'd expect the URL checker to be disabled by default and enabled by a flag.

I'd like to use this in [fed-reference](https://github.com/alexilyaev/fed-reference) but I need the 2 tasks separate (e.g. running Markdown lint on file changes, and the URL check only periodically or during CI or something).

Can you add a flag for the URL checker?

**Comment by giltayar** [comment]
Sure. I'll try and do it today or during the weekend.

**Comment by giltayar** [comment]
Done. But notice that the default is still true. `--no-check-links` will disable the check.
